In [3]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [5]:
import numpy as np

In [18]:
arr=np.array([1,2,3,4,5,6,7])

In [19]:
arr1=arr.copy()

In [20]:
arr1

array([1, 2, 3, 4, 5, 6, 7])

In [21]:
arr[3:]=100

In [22]:
arr

array([  1,   2,   3, 100, 100, 100, 100])

In [23]:
arr1

array([1, 2, 3, 4, 5, 6, 7])

In [24]:
l1=[1,2,3]
l2=[3,4,5]
l3=[4,6,6]
arr1=np.array([l1,l2,l3])

In [25]:
arr1

array([[1, 2, 3],
       [3, 4, 5],
       [4, 6, 6]])

In [27]:
np.ndim(arr1)

2

In [28]:
np.array(arr1,ndmin=10)

array([[[[[[[[[[1, 2, 3],
               [3, 4, 5],
               [4, 6, 6]]]]]]]]]])

In [29]:
np.zeros(4)

array([0., 0., 0., 0.])

In [30]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [31]:
np.ones((2,3),dtype=int)

array([[1, 1, 1],
       [1, 1, 1]])

In [32]:
np.empty(4)

array([0., 0., 0., 0.])

In [33]:
np.empty(2)

array([1.06490544e-311, 0.00000000e+000])

In [34]:
np.arange(4)

array([0, 1, 2, 3])

In [38]:
np.arange(1,6,2)

array([1, 3, 5])

In [39]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [41]:
np.linspace(2,20,5)

array([ 2. ,  6.5, 11. , 15.5, 20. ])

In [43]:
np.random.rand(4)

array([0.32185549, 0.2630277 , 0.07354362, 0.81146671])

In [44]:
np.random.rand(3,5)

array([[0.83659022, 0.91316101, 0.5374899 , 0.92576493, 0.41487704],
       [0.7667433 , 0.3371882 , 0.76538279, 0.48136376, 0.90968585],
       [0.79634878, 0.35527555, 0.68352031, 0.81619584, 0.35317924]])

In [45]:
np.random.randn(3,4)

array([[-0.10045767, -1.5146121 , -0.0931402 ,  1.54525779],
       [-0.52825225,  0.59753413, -0.75027175, -0.46755972],
       [-0.95625579, -0.54385145,  0.0541113 ,  0.33988124]])

In [46]:
np.random.ranf(3)

array([0.27708449, 0.72608301, 0.55716705])

In [47]:
np.random.randint(2,10,2)

array([9, 2], dtype=int32)

In [49]:
np.shape(arr1)

(3, 3)